stages:
  - build
  - test

build-vtkmodule:
  image: kitware/paraview-ci-plugin:vtk-v9.1.0-stdthread-python-mpi
  stage: build
  script:
    - apt-get install -y libcgal-dev libeigen3-dev
    - mkdir -p build
    - cd build
    - cmake -DVTK_DIR=/vtk/build/ -DBUILD_TESTING=ON -DBUILD_PYTHON_WRAPPERS=ON ..
    - cmake --build . --config Release --parallel 2
  tags:
    - build
    - docker
    - linux-x86_64
    - vtk-cgal
  artifacts:
    expire_in: 1h
    when: always
    paths:
      - build/

test-vtkmodule:
  image: kitware/paraview-ci-plugin:vtk-v9.1.0-stdthread-python-mpi
  stage: test
  needs: ['build-vtkmodule']
  script:
    - cd build
    - ctest -VV
  tags:
    - test
    - docker
    - linux-x86_64
    - vtk-cgal
  dependencies:
    - build-vtkmodule

build-pvplugin:
  image: kitware/paraview-for-ci:latest
  stage: build
  script:
      # This is needed because the build of ParaView uses some absolute path
    - ln -s /paraview/gitlab-kitware-sciviz-ci/ /builds/gitlab-kitware-sciviz-ci
    - git submodule update --init --recursive
    - apt update
    - apt-get install -y libcgal-dev libeigen3-dev
    - mkdir -p build
    - cd build
    - cmake -DCMAKE_PREFIX_PATH=/opt/paraview/install/ -DBUILD_TESTING=OFF -DBUILD_PYTHON_WRAPPERS=OFF -DVESPA_BUILD_PV_PLUGIN=ON ..
    - cmake --build . --config Release --parallel 2
  tags:
    - build
    - docker
    - linux-x86_64
    - vtk-cgal
  artifacts:
    expire_in: 1h
    when: always
    paths:
      - build/
