# Static libcurl for the SHYX AI Assistant. paraview_plugin_build sets
# BUILD_SHARED_LIBS ON for VESPAPlugin.dll; force a static libcurl and restore.

include(FetchContent)
set(_vespa_saved_shared_libs "${BUILD_SHARED_LIBS}")
set(_vespa_saved_testing "${BUILD_TESTING}")
set(BUILD_SHARED_LIBS OFF CACHE BOOL "" FORCE)
set(BUILD_TESTING OFF CACHE BOOL "" FORCE)
set(BUILD_CURL_EXE OFF CACHE BOOL "" FORCE)
set(BUILD_EXAMPLES OFF CACHE BOOL "" FORCE)
set(BUILD_LIBCURL_DOCS OFF CACHE BOOL "" FORCE)
set(BUILD_MISC_DOCS OFF CACHE BOOL "" FORCE)
set(ENABLE_CURL_MANUAL OFF CACHE BOOL "" FORCE)
set(CURL_DISABLE_INSTALL ON CACHE BOOL "" FORCE)
set(CURL_ENABLE_EXPORT_TARGET OFF CACHE BOOL "" FORCE)
set(CURL_ENABLE_SSL ON CACHE BOOL "" FORCE)
set(HTTP_ONLY ON CACHE BOOL "" FORCE)
set(BUILD_STATIC_LIBS ON CACHE BOOL "" FORCE)
set(PICKY_COMPILER OFF CACHE BOOL "" FORCE)
set(CURL_USE_LIBPSL OFF CACHE BOOL "" FORCE)
set(CURL_USE_LIBSSH2 OFF CACHE BOOL "" FORCE)
set(CURL_USE_LIBSSH OFF CACHE BOOL "" FORCE)
set(USE_LIBIDN2 OFF CACHE BOOL "" FORCE)
set(CURL_ZLIB OFF CACHE BOOL "" FORCE)
set(CURL_BROTLI OFF CACHE BOOL "" FORCE)
set(CURL_ZSTD OFF CACHE BOOL "" FORCE)
set(USE_NGHTTP2 OFF CACHE BOOL "" FORCE)
if (WIN32)
  set(CURL_USE_SCHANNEL ON CACHE BOOL "" FORCE)
  set(CURL_WINDOWS_SSPI ON CACHE BOOL "" FORCE)
  set(CURL_USE_OPENSSL OFF CACHE BOOL "" FORCE)
endif ()
FetchContent_Declare(vespa_curl
  GIT_REPOSITORY https://github.com/curl/curl.git
  GIT_TAG curl-8_21_0
  GIT_SHALLOW TRUE)
FetchContent_MakeAvailable(vespa_curl)
set(BUILD_SHARED_LIBS OFF CACHE BOOL "Build shared library" FORCE)
set(BUILD_SHARED_LIBS "${_vespa_saved_shared_libs}")
if (_vespa_saved_testing)
  set(BUILD_TESTING ON CACHE BOOL "Build Testing" FORCE)
else ()
  set(BUILD_TESTING OFF CACHE BOOL "Build Testing" FORCE)
endif ()
unset(_vespa_saved_shared_libs)
unset(_vespa_saved_testing)
if (NOT TARGET CURL::libcurl AND TARGET libcurl_static)
  add_library(CURL::libcurl ALIAS libcurl_static)
endif ()

target_link_libraries(VESPAPlugin PRIVATE CURL::libcurl)
if (WIN32)
  target_link_libraries(VESPAPlugin PRIVATE
    ws2_32 crypt32 secur32 advapi32 bcrypt normaliz iphlpapi)
endif ()
