NAME
  vtkCGALPMP
DESCRIPTION
  "This module contains filters related to the PolygonMeshProcessing module of CGAL."
GROUPS
  Meshing
DEPENDS
  VTK::CommonCore
  VTK::CommonDataModel
  VTK::CommonExecutionModel
  VTK::FiltersCore
  VTK::FiltersExtraction
  CGAL::CGAL
OPTIONAL_DEPENDS
  # one of them should be found depending on CGAL version
  CGAL::Eigen3_support
  Eigen3::Eigen
TEST_DEPENDS
  VTK::CommonSystem
  VTK::FiltersSources
  VTK::IOXML
  VTK::TestingCore
